import React from 'react';
import LayoutProvider from '@library/layouts/LayoutProvider';
import Navigation from '@library/components/Navigation';
import Footer from '@library/components/Footer';

interface Props {}

const About: React.FC = () => {
	// refactor
	return (
		<LayoutProvider
			classContainer='font-family-helveltica bg-gray-100 max-w-8xl mx-auto p-4 sm:px-6 lg:px-8'
			footerElement={<Footer />}
			navigationElement={<Navigation />}
		>
			<div className='bg-white p-10'>
				<div className='text-4xl font-bold pb-4'>About Us 🚀</div>
				<p className='text-xl'>
					Welcome to Collab, a thriving community for developers, creators, and
					tech enthusiasts to learn, share, and grow together.
				</p>
				<p className='text-xl'>
					We believe that knowledge should be open, collaboration should be
					encouraged, and everyone—regardless of experience level—should have a
					voice.
				</p>
				<p className='text-xl'>
					Whether you're a beginner taking your first steps into coding or a
					seasoned developer sharing insights, this platform is built for you.
				</p>

				<div className='text-3xl font-bold py-4'>What We Offer </div>
				<ul className='text-xl'>
					<li>
						✅ Open Learning – Share tutorials, insights, and experiences.{' '}
					</li>
					<li>
						{' '}
						✅ Engaging Discussions – Connect with like-minded professionals.
					</li>
					<li>
						{' '}
						✅ Collaboration – Find contributors, get feedback, and build
						together.{' '}
					</li>
					<li>
						✅ Career Growth – Showcase your expertise and network with
						industry leaders.
					</li>
				</ul>
				<div className='text-3xl font-bold py-4'>Join the Community! </div>
				<p className='text-xl'>
					We are more than just a website; we are a movement. A space where
					ideas flourish, innovations emerge, and knowledge is shared freely.
					<p>💡Start writing, sharing, and Happy coding ❤️</p>
				</p>
				<p className='py-6 text-sm italic text-gray-400'>
					******Description about text is generated by ChatGPT******
				</p>
			</div>
		</LayoutProvider>
	);
};

export default About;
